// Deep training pool — authored + adversarially reviewed for the Training Room.
// 34 items across spot / fix / calibrate and all ten skills. DS-flavored,
// fictional data. Generated content; edit here, then it syncs on build.
import type { DrillSeed } from "./drills";

export const DRILL_POOL: DrillSeed[] = [
  {
    title: "Focus Mode and retention",
    mode: "spot",
    skill: "cause",
    difficulty: 1,
    contextSnippet: "**Nimbus Notes, 30-day retention:** users who enabled Focus Mode retain at **68%** vs **44%** for those who didn't. Focus Mode is **opt-in** (self-selected); no experiment was run.",
    sourceLabel: "Product analytics dashboard (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "The data is an observational split on a self-selected feature: adopters and non-adopters differ in ways beyond Focus Mode (motivation, tenure, engagement). The faithful version reports the 68% vs 44% association and flags self-selection; the overclaim promotes that association to a causal lift ('lifts retention') with no experiment or control. Same numbers, causal grammar the data can't earn.",
    faithfulText: "Users who opted into Focus Mode retain at 68% vs 44% for non-adopters — a strong association, though adopters self-selected into the feature.",
    overclaimedText: "Enabling Focus Mode lifts 30-day retention from 44% to 68%.",
    device: "reading a causal lift from a self-selected adoption split with no experiment",
  },
  {
    title: "Onboarding v2 and activation",
    mode: "spot",
    skill: "cause",
    difficulty: 3,
    contextSnippet: "**Signup flow — onboarding v2 shipped May 1 to 100% of new signups:** week-4 activation **51%** (April cohorts) → **59%** (May cohorts). **No holdback group.** May also carried a seasonal enrollment spike.",
    sourceLabel: "Growth experimentation log (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "This is a before/after shift with no counterfactual — the change rolled to 100% with no holdback, and May brought a seasonal spike that also lifts activation. The faithful telling reports the 51%→59% rise 'coinciding with' the launch and names the missing holdback; the overclaim says v2 'raised' activation, crediting the launch for a movement no control group isolates. The move hides that a full rollout can't distinguish the feature from the calendar.",
    faithfulText: "Week-4 activation rose from 51% to 59% between April and May cohorts, coinciding with the onboarding v2 launch — though there was no holdback and May carried a seasonal spike.",
    overclaimedText: "Onboarding v2 raised week-4 activation from 51% to 59%.",
    device: "crediting a before/after shift to the launch with no holdback or counterfactual",
  },
  {
    title: "What lifted checkout conversion",
    mode: "spot",
    skill: "single_cause",
    difficulty: 2,
    contextSnippet: "**Checkout funnel, Q3:** conversion **2.1% → 2.8%**. Same quarter, three things shipped: **one-click checkout**, a **lower free-shipping threshold** ($75→$50), and **paid-search budget +40%**.",
    sourceLabel: "E-commerce funnel report (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "Three conversion-affecting changes landed in the same quarter, so the 2.1%→2.8% gain can't be assigned to any one of them. The faithful version lists all three alongside the lift; the overclaim credits one-click checkout alone, a single-cause claim the bundled rollout can't support. The numbers are identical — only the attribution narrows past the evidence.",
    faithfulText: "Checkout conversion rose from 2.1% to 2.8% in Q3, alongside one-click checkout, a lower free-shipping threshold, and a 40% increase in paid-search budget.",
    overclaimedText: "One-click checkout drove checkout conversion from 2.1% to 2.8% in Q3.",
    device: "crediting one change when three conversion drivers shipped together",
  },
  {
    title: "What moved the fraud model's AUC",
    mode: "spot",
    skill: "single_cause",
    difficulty: 3,
    contextSnippet: "**Fraud model v4:** test AUC **0.81 → 0.86**. Changes this cycle: added **12 velocity features**, expanded the **training window 6→12 months**, and switched **XGBoost→LightGBM**. **No ablation** was run to isolate the contributions.",
    sourceLabel: "ML model release notes (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "Three things changed at once — features, training data, and algorithm — and without an ablation none can claim the 0.05 AUC gain. The faithful telling attributes the lift to the cycle as a whole and notes no ablation isolates the pieces; the overclaim hands the full gain to the velocity features, the intuitive-but-unproven single cause. The doubled training window and the LightGBM swap are easy to forget, which is exactly why the move slips past.",
    faithfulText: "Test AUC rose from 0.81 to 0.86 after a cycle that added 12 velocity features, doubled the training window, and switched to LightGBM — no ablation isolates each change's share.",
    overclaimedText: "The 12 new velocity features lifted the fraud model's test AUC from 0.81 to 0.86.",
    device: "assigning the full AUC gain to one of three simultaneous model changes with no ablation",
  },
  {
    title: "Two weeks of WAU",
    mode: "spot",
    skill: "extrapolation",
    difficulty: 1,
    contextSnippet: "**Nimbus Analytics:** weekly active users 8,200 (week 1) → 9,100 (week 2), **+11% WoW**. Product launched 3 weeks ago.",
    sourceLabel: "Growth dashboard (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "The data is a single interval: two points, 8,200 to 9,100. 'Compounding 11% a week' and the Q4 projection treat one week-over-week move as a durable growth rate — and early-product numbers are the noisiest you will ever read. The faithful version reports the change; it does not annualize a single step.",
    faithfulText: "WAU rose 11% week-over-week, 8,200 to 9,100 — one week of change on a three-week-old product.",
    overclaimedText: "WAU is compounding 11% a week; hold that pace and we clear 15,000 by Q4.",
    device: "projecting a sustained growth curve from a single week-over-week change (two points)",
  },
  {
    title: "Checkout test, day 4",
    mode: "spot",
    skill: "certainty",
    difficulty: 2,
    contextSnippet: "**Checkout A/B test — day 4 of 14:** variant B **4.2%** conversion vs control **3.8%** · ~1,900 sessions/arm · **p=0.19** · 95% CI on lift **[-0.2pt, +1.0pt]**.",
    sourceLabel: "Experimentation platform (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "The confidence interval on the lift straddles zero and p=0.19 — this is a peek, not a verdict, and the test is powered for 14 days. 'Lifts conversion... ship it' converts a noisy interim reading into a decision the data has not earned. Speaking a provisional result as settled is the move; the figures are fine, the certainty is not.",
    faithfulText: "Four days in, B leads by 0.4pt but the interval still straddles zero (p=0.19) — inconclusive until the full 14 days land.",
    overclaimedText: "Variant B lifts conversion from 3.8% to 4.2%; ship it.",
    device: "stating a provisional, non-significant mid-test reading as a settled effect",
  },
  {
    title: "320 called it confusing",
    mode: "spot",
    skill: "base_rate",
    difficulty: 1,
    contextSnippet: "**In-app feedback, June:** 320 users tagged the redesigned dashboard \"confusing.\" Monthly active users: **48,000**.",
    sourceLabel: "Product feedback tool (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "320 sounds like a crowd until you divide by 48,000 MAU — it is 0.7%, and only from users who volunteered feedback at all. 'Clearly backfiring' leans entirely on the bare count; the rate tells a far quieter story. Dropping the denominator is the whole overreach.",
    faithfulText: "320 of 48,000 MAU (0.7%) tagged the redesign \"confusing\" this month.",
    overclaimedText: "320 users called the redesign confusing — the change is clearly backfiring.",
    device: "citing a raw complaint count with the denominator dropped",
  },
  {
    title: "An NPS of 62",
    mode: "spot",
    skill: "extrapolation",
    difficulty: 3,
    contextSnippet: "**Q2 relationship survey:** NPS **62** from **40 enterprise admins** (response rate 55%). Enterprise = **6% of accounts**; no survey sent to Solo or Team tiers.",
    sourceLabel: "Customer insights deck (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "62 describes 40 admins in a tier that is 6% of accounts — 'our NPS' quietly annexes the 94% who were never surveyed, tiers that routinely skew very differently. The score is real for enterprise; the company-wide scope in 'our' is invented. Subtle because a headline NPS feels like a fact about the whole base.",
    faithfulText: "Enterprise admins scored NPS 62 in Q2; the other 94% of accounts (Solo and Team) were not surveyed.",
    overclaimedText: "Our NPS is 62.",
    device: "generalizing one narrow cohort's score to the entire customer base",
  },
  {
    title: "Team vs Solo adoption",
    mode: "spot",
    skill: "base_rate",
    difficulty: 3,
    contextSnippet: "**Feature X, first 30 days:** Team plan **890 adopters** · Solo plan **340 adopters**. Seats: Team **12,000**, Solo **3,000**.",
    sourceLabel: "Adoption analytics (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "Team wins on the raw count but loses on the rate: 7.4% (890/12,000) versus Solo's 11.3% (340/3,000), because Team has four times the seats. 'Landed best with Team' reads the bigger number as bigger enthusiasm — the dropped denominator flips the actual conclusion. Subtle because the raw count points confidently the wrong way.",
    faithfulText: "Normalized to seats, adoption ran higher on Solo (340/3,000 = 11.3%) than Team (890/12,000 = 7.4%), despite Team's larger raw count.",
    overclaimedText: "Feature X landed best with Team users — 890 adopters vs 340 on Solo.",
    device: "comparing raw counts across groups of unequal size without normalizing to a rate",
  },
  {
    title: "Dark mode and retention",
    mode: "fix",
    skill: "cause",
    difficulty: 2,
    contextSnippet: "**Lumen (fictional note-taking app):** 30-day retention — dark-mode users **68%** vs light-mode users **51%** (17pt gap). Dark mode is opt-in; users chose it themselves. Flawed telling: *\"Dark mode lifts 30-day retention 17 points — make it the default and retention climbs.\"*",
    sourceLabel: "Product analytics dashboard (fictional)",
    prompt: "The telling reads a self-selected gap as proof the feature causes retention. Pick the rewrite that stays true to the data without going soft.",
    explanation: "The data shows an association between two things engaged users do (pick dark mode, stick around), not that one causes the other — dark-mode users may simply be power users who'd retain regardless. The flawed telling launders correlation into a causal 'lifts.' The repair keeps the 17pt gap but names the self-selection and points to the test that would actually settle causation.",
    device: "reading a self-selected correlation as causation",
    choices: [
      { text: "Dark-mode users retain 17 points higher, but they opted in themselves — an A/B test that defaults new users into dark mode would show whether the feature drives retention or just marks already-engaged users.", correct: true, rationale: "Keeps the real gap, names the selection problem, and points to the experiment that isolates cause. True and still useful." },
      { text: "Dark-mode users retain 17 points better, most likely because the reduced screen glare keeps them in longer nightly sessions.", correct: false, rationale: "Trades one unsupported causal story for a more specific one — invents a mechanism the data never measured." },
      { text: "Retention differs between dark and light users, but with opt-in we can conclude nothing about the feature.", correct: false, rationale: "Over-hedged into uselessness — a 17pt gap is a real signal worth testing, not nothing." },
      { text: "Dark mode raises 30-day retention by 17 points; roll it out as the default to capture the lift.", correct: false, rationale: "Still asserts causation and a rollout action straight from a correlation — the original flaw untouched." },
    ],
  },
  {
    title: "What drove the Q3 revenue jump",
    mode: "fix",
    skill: "single_cause",
    difficulty: 3,
    contextSnippet: "**Cascade Commerce (fictional B2B tool):** Q3 revenue **+22% QoQ**. Same quarter: pricing page redesign shipped (Jul), enterprise reseller partnership went live (Aug), paid ad spend **+40%**, and Q3 is the historical seasonal peak. Flawed telling: *\"The pricing-page redesign drove the 22% Q3 revenue jump.\"*",
    sourceLabel: "Revenue ops review deck (fictional)",
    prompt: "Four things moved at once and the telling credits one. Pick the rewrite that stays true to the data without going soft.",
    explanation: "The redesign, a +40% ad-spend hike, a new partnership, and seasonality all landed in the same quarter, so no single one owns the 22% — crediting the pricing page is an unsupported attribution. The repair preserves the headline number but makes the confound explicit, which is what actually guides the next move (isolate the drivers). Swapping in a different single cause (ad spend) is the same error wearing a different hat.",
    device: "crediting one driver when several moved together",
    choices: [
      { text: "Revenue rose 22% in Q3, but the redesign shipped alongside a +40% ad-spend increase, a new reseller partnership, and the seasonal peak — we can't credit any single driver without isolating their contributions.", correct: true, rationale: "Keeps the 22% and names the concurrent movers, setting up attribution work. Honest and still actionable." },
      { text: "Revenue rose 22% in Q3, most likely driven by the +40% ad-spend increase given how large that lever is.", correct: false, rationale: "Just relabels the single-cause story — still isolates one driver on a hunch, not evidence." },
      { text: "Revenue changed in Q3 for a mix of reasons we can't untangle, so the number isn't worth reporting.", correct: false, rationale: "Over-hedged — a 22% lift is very much worth reporting; the caveat is about attribution, not the fact." },
      { text: "The pricing redesign was the primary driver of the 22% lift, with the other factors playing minor roles.", correct: false, rationale: "Still asserts a rank order the data doesn't support — the original overreach with softer adjectives." },
    ],
  },
  {
    title: "Projecting the pilot",
    mode: "fix",
    skill: "extrapolation",
    difficulty: 2,
    contextSnippet: "**Northwind Logistics (fictional routing feature):** Beta pilot — **3 enterprise accounts**, **14 days**, median task-completion time down **15%**. Flawed telling: *\"The feature saves the average customer 15% annually — projected across the base, that's a major efficiency win.\"*",
    sourceLabel: "Beta program readout (fictional)",
    prompt: "A 3-account, 2-week result gets stretched to every customer for a full year. Pick the rewrite that stays true to the data without going soft.",
    explanation: "Three self-selected accounts over two weeks cannot support 'the average customer' or an 'annual' figure — the sample and window are far too narrow for that reach. The flawed telling projects a promising local reading across the whole base and a full year. The repair keeps the 15% as a pilot signal and scopes it to what was actually measured, then names the rollout that would license a broader claim.",
    device: "projecting a tiny short-window sample to the whole base and a full year",
    choices: [
      { text: "In a 3-account, 2-week pilot, median task time fell 15% — a promising early signal, but too small and short to project to the full base or a full year without a wider rollout.", correct: true, rationale: "Reports the real result, scopes it to the sample, and names what would justify going broader. Useful and honest." },
      { text: "All three pilot accounts improved, so we can expect a 15% gain across every customer once we scale.", correct: false, rationale: "Still extrapolates — 'three of three' with n=3 is exactly the leap the fix should stop." },
      { text: "The pilot is far too small to tell us anything meaningful about the feature.", correct: false, rationale: "Over-hedged — a consistent 15% across three accounts is a real signal worth advancing, not nothing." },
      { text: "Task time fell 15% in the pilot because the simpler routing UI cut decision overhead.", correct: false, rationale: "Introduces a causal mechanism the pilot never isolated — a different flaw, not a scoping fix." },
    ],
  },
  {
    title: "Calling the A/B test early",
    mode: "fix",
    skill: "certainty",
    difficulty: 3,
    contextSnippet: "**Fathom (fictional checkout flow):** A/B test — variant B conversion **4.1%** vs control **3.9%** (+0.2pt), **p = 0.18**, at **60%** of planned sample size. Flawed telling: *\"Variant B wins by 0.2 points — ship it.\"*",
    sourceLabel: "Experimentation platform (fictional)",
    prompt: "A provisional, not-yet-significant reading gets spoken as a settled result. Pick the rewrite that stays true to the data without going soft.",
    explanation: "At p = 0.18 and 60% of the target sample, the +0.2pt is a noisy interim reading, not a decided winner — 'wins, ship it' treats provisional as settled. The repair reports the direction and magnitude honestly while flagging that the test hasn't cleared its own bar yet. Predicting it 'will' reach significance is the same certainty error aimed at the future.",
    device: "speaking a noisy interim reading as a settled result",
    choices: [
      { text: "Variant B is trending +0.2pt, but at p = 0.18 and only 60% of the planned sample it isn't conclusive yet — keep the test running before making a call.", correct: true, rationale: "States direction and magnitude, flags the non-significance and incomplete sample, and gives a clear next step. Honest without abandoning the signal." },
      { text: "Variant B is on track to reach significance and win — we can start planning the rollout now.", correct: false, rationale: "Just relocates the false certainty to a prediction; the interim result licenses no such forecast." },
      { text: "The test shows no difference between the variants, so we should drop B.", correct: false, rationale: "Over-reads the other way — 'not yet significant' is not 'no difference,' and killing it discards a live signal." },
      { text: "Variant B leads by 0.2 points; ship it and monitor conversion afterward.", correct: false, rationale: "Still ships on an inconclusive reading — the original overclaim with a monitoring fig leaf." },
    ],
  },
  {
    title: "Fraud alerts up 300%",
    mode: "fix",
    skill: "base_rate",
    difficulty: 1,
    contextSnippet: "**Tiller Payments (fictional):** Flagged-fraud alerts rose from **2 last month to 8 this month (+300%)**, across **45,000 transactions** (alert rate **0.018%**). Flawed telling: *\"Fraud alerts are up 300% month over month — we have a serious fraud problem.\"*",
    sourceLabel: "Risk monitoring report (fictional)",
    prompt: "A big percentage rides on a tiny raw count with the denominator dropped. Pick the rewrite that stays true to the data without going soft.",
    explanation: "The '300%' is 2 alerts becoming 8 out of 45,000 transactions — a 0.018% rate — so the percentage magnifies a handful of cases into a false crisis. Restoring the denominator reframes it as a small, watch-worthy uptick rather than a surge. Dismissing it entirely overcorrects; the honest telling keeps both the raw movement and the base rate in view.",
    device: "reporting a percentage change with the denominator dropped",
    choices: [
      { text: "Fraud alerts rose from 2 to 8 (of 45,000 transactions) — a real uptick worth watching, but at a 0.018% rate the '300%' reflects small raw numbers, not a fraud surge.", correct: true, rationale: "Restores the denominator, keeps the movement visible, and right-sizes the concern. True and still actionable." },
      { text: "Fraud is up 300% month over month — escalate to the risk team immediately.", correct: false, rationale: "Repeats the denominator-free percentage and the false-alarm escalation it triggers." },
      { text: "Only 8 alerts on 45,000 transactions — this is noise, nothing to look at.", correct: false, rationale: "Over-hedged the other way — a 4x raw jump still merits a look even if the rate is low." },
      { text: "Alerts quadrupled this month, likely because of the new payment provider onboarded in the same window.", correct: false, rationale: "Adds an unsupported causal explanation — a new flaw rather than a base-rate fix." },
    ],
  },
  {
    title: "The activation number nobody read",
    mode: "fix",
    skill: "buried_lede",
    difficulty: 2,
    contextSnippet: "**NorthBay Analytics, onboarding cohort (n=1,840 new signups, May):** activation rate (completed first report within 7 days) fell to **48%**, down from 61% in April. Support ticket volume flat. Time-to-first-login unchanged.\n\n*Flawed telling:* \"This month we continued monitoring the onboarding funnel across several dimensions. Support tickets held steady and time-to-first-login was unchanged from prior periods, consistent with a stable top of funnel. Drilling into the activation step, we observed that the rate at which new signups completed their first report within seven days came in at 48%, compared with 61% in April.\"",
    sourceLabel: "Growth analytics dashboard (fictional)",
    prompt: "The finding is accurate but the 13-point activation drop is stranded in the last sentence behind stable-metric throat-clearing. Pick the rewrite that leads with the point without going soft.",
    explanation: "The original is honest and correctly caveated, but it makes the reader wade through two null results before the one number that matters. The craft fix is to front-load the 48%-from-61% drop and demote the stable metrics to context. The move is ordering, not overreach — the correct rewrite changes sequence only, keeping every figure and caveat intact.",
    device: "the key result (a 13-point activation drop) buried behind stable-metric preamble",
    choices: [
      { text: "Activation dropped hard in May: 48% of new signups completed a first report within 7 days, down from 61% in April — a 13-point fall. Support volume and time-to-first-login were flat, so the break is in the activation step, not top of funnel.", correct: true, rationale: "Leads with the number that moved, then uses the flat metrics to localize the problem. Same data, same caveats, no overreach — just fixed order." },
      { text: "Onboarding was mixed in May. Some metrics held steady while others shifted, and the activation step in particular is worth a closer look as we head into next month.", correct: false, rationale: "Over-hedged into uselessness — it buries the finding even deeper by refusing to state the 48%/61% numbers at all." },
      { text: "Activation cratered to 48% in May because the April onboarding changes broke the first-report flow. Fixing that flow should restore the 13 points.", correct: false, rationale: "Fixes the ordering but introduces a new flaw — it invents an unsupported cause and a guaranteed recovery the data never established." },
      { text: "In May we tracked activation alongside support tickets and login timing; the headline is that activation, one of the several funnel metrics we watch, moved to 48% versus 61% in April.", correct: false, rationale: "Still throat-clears through the other metrics before the number and softens it as merely 'one of several' — the lede stays buried." },
    ],
  },
  {
    title: "NPS to the hundredth",
    mode: "fix",
    skill: "false_precision",
    difficulty: 2,
    contextSnippet: "**Cirrus Fitness app, in-app NPS survey (n=214 respondents, June):** promoters 118, passives 61, detractors 35. Reported NPS = **38.79%**, \"up 4.21 points from May.\" Survey is opt-in; response rate 6%.\n\n*Flawed telling:* \"June NPS landed at 38.79%, an improvement of 4.21 points over May's 34.58%.\"",
    sourceLabel: "Product research tracker (fictional)",
    prompt: "The arithmetic is correct but the decimals imply precision a 214-person opt-in survey can't carry. Pick the rewrite that reports the number honestly without throwing it away.",
    explanation: "NPS on n=214 has a sampling margin of roughly plus or minus 7 points; reporting 38.79 and a 4.21-point change dresses noise as a measured quantity. The fix rounds to whole points and flags that the move is within noise — keeping the finding usable without the fake exactness. The distractors either keep the spurious decimals, discard the number entirely, or over-claim a real improvement.",
    device: "reporting NPS and its change to hundredths when a small opt-in sample supports only whole-point resolution",
    choices: [
      { text: "June NPS was about 39, versus roughly 35 in May. With n=214 the margin is around plus or minus 7 points, so treat the ~4-point rise as directional, not a confirmed gain.", correct: true, rationale: "Rounds to the resolution the sample supports and names the uncertainty, while still reporting the level and direction. Honest and useful." },
      { text: "June NPS improved to 38.79%, and while we should note the sample is modest, the 4.21-point lift is a genuine step up from May.", correct: false, rationale: "Keeps the false precision and, worse, asserts a 'genuine step up' the margin of error doesn't support." },
      { text: "NPS moved in June, but with a 6% response rate and an opt-in panel we can't really say anything about the level, so no number is reportable.", correct: false, rationale: "Over-corrects into uselessness — a noisy estimate is still an estimate; refusing to report the ~39 throws away real information." },
      { text: "June NPS rose 4.2 points to 38.8%, our strongest month-over-month gain this quarter.", correct: false, rationale: "Trims one decimal but keeps the spurious precision and adds an unsupported superlative on top." },
    ],
  },
  {
    title: "The p95 that goes nowhere",
    mode: "fix",
    skill: "missing_sowhat",
    difficulty: 3,
    contextSnippet: "**Halcyon checkout API, latency audit (7-day window, 2.1M requests):** p50 140ms, p95 **920ms** (SLA target 500ms), p99 1.8s. The p95 breaches concentrate in the 6–9pm window and trace to the tax-calculation call. Cart-abandon rate in that window is 3.2pts above daily average.\n\n*Flawed telling:* \"p95 checkout latency is 920ms against a 500ms target, breaching mostly during the 6–9pm peak, and the breaches trace cleanly to the tax-calculation service call. Abandonment in that window runs 3.2 points above average. All figures are from a full 7-day, 2.1M-request window.\"",
    sourceLabel: "SRE performance review (fictional)",
    prompt: "The telling is accurate and well-sourced but stops at description — it names no decision. Pick the rewrite that adds the so-what without overreaching the evidence.",
    explanation: "Everything stated is true and even localizes cause and cost, yet it hands the reader a fact with no ask — a classic missing-so-what. The fix names the decision the numbers point to (prioritize the tax-call path for the peak window) while keeping the abandonment link as association, not proven causation. Distractors either stay purely descriptive, overclaim the revenue causation, or bury the recommendation in hedges.",
    device: "a true, well-sourced latency finding that names no decision or next action",
    choices: [
      { text: "p95 checkout latency (920ms vs 500ms SLA) breaches during 6–9pm and traces to the tax-calculation call; abandonment runs 3.2pts higher in that window. Recommend prioritizing optimization or caching of the tax call for the peak window as this quarter's reliability bet, and instrumenting to test whether cutting latency moves abandonment.", correct: true, rationale: "Turns the finding into a decision — where to spend effort — and treats the abandonment link as a hypothesis to test, not a proven cause. Useful without overreaching." },
      { text: "p95 checkout latency is 920ms against a 500ms target, concentrated in the 6–9pm window and traced to the tax-calculation call, with abandonment 3.2 points higher there. These figures are drawn from a full 7-day, 2.1M-request sample.", correct: false, rationale: "Still stops at description — reordered and trimmed, but it names no decision, which is the exact flaw." },
      { text: "The tax-calculation call is costing us 3.2 points of abandonment every evening; fixing its latency will recover that revenue and bring us back under SLA.", correct: false, rationale: "Adds an action but overreaches — it converts an association into a guaranteed revenue recovery the data never established." },
      { text: "There may be an opportunity to look into the tax-calculation call at some point, though we'd want more data before deciding whether it's worth anyone's time this quarter.", correct: false, rationale: "Hedges the so-what into non-existence; the SLA breach and localized cause already justify acting, so this is over-soft." },
    ],
  },
  {
    title: "The lift with no window",
    mode: "fix",
    skill: "absent_caveat",
    difficulty: 3,
    contextSnippet: "**Vantage e-commerce, recommendation-widget A/B test:** treatment +6.4% revenue-per-session vs control (p=0.03, n≈40k/arm). Test ran **9 days**, all within a promotional sale that ended when the test ended. Novelty of the widget not separately measured.\n\n*Flawed telling:* \"The new recommendation widget lifted revenue-per-session 6.4% (p=0.03). Recommend shipping to 100%.\"",
    sourceLabel: "Experimentation platform (fictional)",
    prompt: "The result is real and the recommendation is reasonable, but one limitation is silently dropped. Pick the rewrite that restores the missing caveat without gutting the recommendation.",
    explanation: "The 6.4% lift is statistically real, but the entire test sat inside a promo sale that ended with it — so the effect may not hold at baseline traffic, a caveat the telling omits. The fix keeps the ship recommendation but conditions it on confirming the lift outside the promo (a holdback or follow-up). Distractors drop the caveat, kill the recommendation entirely, or invent an unrelated concern.",
    device: "omitting that the measured lift occurred entirely inside a promo period that ended with the test",
    choices: [
      { text: "The widget lifted revenue-per-session 6.4% (p=0.03), but the full 9-day test ran inside a promo sale, so we can't yet separate widget effect from promo lift. Recommend shipping behind a small holdback to confirm the effect persists at baseline traffic before going to 100%.", correct: true, rationale: "Restores the missing confound caveat and keeps a concrete, still-actionable recommendation — ship with a holdback to verify. Honest and useful." },
      { text: "The widget lifted revenue-per-session 6.4% (p=0.03). Recommend shipping to 100% given the clear statistical significance.", correct: false, rationale: "Leaves the promo-window confound unstated — the exact craft flaw — and leans on significance to justify skipping it." },
      { text: "The widget showed a 6.4% lift, but because the test ran only 9 days on 40k sessions per arm, the sample is too small and short to act on. Hold off shipping.", correct: false, rationale: "Names the wrong limitation — the sample is well-powered (p=0.03) — and over-corrects into inaction. The real caveat is the promo confound, not size." },
      { text: "The widget lifted revenue-per-session 6.4% during a promotional period, which likely means it will perform even better once the sale ends and prices normalize. Ship to 100%.", correct: false, rationale: "Acknowledges the promo but spins it into an unsupported optimistic claim — the opposite of a caveat, and pure speculation." },
    ],
  },
  {
    title: "Six sentences for one number",
    mode: "fix",
    skill: "padding",
    difficulty: 1,
    contextSnippet: "**Quill note-taking app, D30 retention:** the March signup cohort held **D30 retention of 22%**, versus 19% for the February cohort. Cohorts sized ~12k each; measurement method unchanged.\n\n*Flawed telling:* \"After extensive and careful analysis of our cohort data, leveraging a robust and comprehensive methodology, we are pleased to be able to report that, following a detailed examination across the relevant time horizon, the March cohort's thirty-day retention metric has, encouragingly, come in at a level of 22%, which, when contextualized against the prior February cohort's comparable figure of 19%, represents a meaningful and directionally positive movement worth noting.\"",
    sourceLabel: "Lifecycle analytics report (fictional)",
    prompt: "The content is correct but drowned in rigor-signaling filler. Pick the rewrite that says it tight without dropping anything real.",
    explanation: "The telling inflates a two-number comparison into a paragraph of throat-clearing ('robust,' 'comprehensive,' 'we are pleased') that adds no information and hides the point. The fix states the 22%-vs-19% move and its size plainly. Distractors keep the padding, over-trim to the point of dropping the comparison, or pad differently by tacking on an unsupported cause.",
    device: "a one-line retention comparison bloated with rigor-signaling filler that drowns the point",
    choices: [
      { text: "D30 retention rose to 22% for the March cohort, up from 19% in February — a 3-point gain on cohorts of ~12k each.", correct: true, rationale: "Says everything the original did — both numbers, the delta, the sample size — in one clean sentence. The point survives, the filler doesn't." },
      { text: "After a thorough and methodologically sound review, we're encouraged to note that March D30 retention reached a solid 22%, a genuinely positive signal relative to February.", correct: false, rationale: "Still padded with 'thorough,' 'methodologically sound,' 'encouraged,' 'genuinely positive' — and it even drops the 19% comparison figure." },
      { text: "Retention improved this month.", correct: false, rationale: "Over-trimmed — it discards both numbers and the delta, leaving nothing actionable. Tight isn't the same as empty." },
      { text: "D30 retention jumped to 22% from 19%, driven by our March onboarding improvements finally paying off.", correct: false, rationale: "Tight, but swaps filler for a new flaw — an unsupported causal claim the data never established." },
    ],
  },
  {
    title: "Openers retained better",
    mode: "calibrate",
    skill: "cause",
    difficulty: 2,
    contextSnippet: "**Nimbus Analytics — 4,200 signups, 90-day window:** users who opened the onboarding email (n=1,900) retained **68%**; non-openers (n=2,300) retained **51%**. Email open was self-selected — no randomization or holdout.",
    sourceLabel: "Lifecycle analytics dashboard (fictional)",
    prompt: "What is the strongest claim this data actually supports?",
    explanation: "The split is observational and self-selected: the same engaged users who open onboarding email are the ones likely to stick around anyway. The 17-point gap is a real association, but attributing it to the email — or projecting a lift from making people open it — assumes a causal effect a self-selected split cannot show. The strongest honest claim states the association and flags the confound.",
    choices: [
      { text: "Retention differed between email openers and non-openers.", correct: false, rationale: "Too weak. True, but it throws away the direction and magnitude the data clearly shows; it under-claims what you can safely say." },
      { text: "Opening the onboarding email is associated with ~17 points higher 90-day retention, but because openers self-selected, the gap isn't necessarily caused by the email.", correct: true, rationale: "Just right. States the size and direction of the association and flags the self-selection confound — the strongest claim an observational split supports." },
      { text: "Opening the onboarding email raises 90-day retention by 17 points.", correct: false, rationale: "Over the line. A causal verb on a self-selected, non-randomized split — this is exactly the correlation-to-causation jump." },
      { text: "Prompting more users to open the email would lift retention by about 17 points.", correct: false, rationale: "Over the line. Assumes causation and that an intervention on non-openers would reproduce the engaged group's outcome." },
    ],
  },
  {
    title: "Slow-dashboard complaints",
    mode: "calibrate",
    skill: "base_rate",
    difficulty: 2,
    contextSnippet: "**Support desk, QoQ:** tickets mentioning \"slow dashboard\" rose **310 → 480**. Total tickets over the same period rose **9,500 → 12,000** (share: 3.3% → 4.0%).",
    sourceLabel: "Support ops report (fictional)",
    prompt: "What is the strongest claim this data actually supports?",
    explanation: "Raw mention counts rose 55%, but total ticket volume rose 26% at the same time — so most of the count growth is just more tickets overall. Normalized, the complaint's share went 3.3% to 4.0%: real, but modest. Quoting the 55% count jump drops the denominator and inflates the trend.",
    choices: [
      { text: "\"Slow dashboard\" mentions rose from 310 to 480 tickets this quarter.", correct: false, rationale: "Too weak / misleading. Accurate count, but stated as a trend it hides that overall ticket volume also grew — the denominator is missing." },
      { text: "As a share of all tickets, \"slow dashboard\" complaints rose from 3.3% to 4.0% — a modest but real increase.", correct: true, rationale: "Just right. Normalizes by ticket volume, so the increase reflects a genuine shift, not just more tickets." },
      { text: "Complaints about the slow dashboard surged 55%, making it a fast-growing pain point.", correct: false, rationale: "Over the line. The 55% is raw-count growth; ~half of it is just higher overall volume. It reads as a spike the share doesn't support." },
      { text: "The slow dashboard is now users' top complaint.", correct: false, rationale: "Over the line. The data gives no ranking of complaint categories — this claim isn't in the readout at all." },
    ],
  },
  {
    title: "Checkout pilot lift",
    mode: "calibrate",
    skill: "extrapolation",
    difficulty: 2,
    contextSnippet: "**Checkout redesign pilot:** 3 test stores vs matched controls, 2 weeks. Conversion **4.8%** (test) vs **4.1%** (control), ~+0.7pt. All 3 test stores are urban flagships. Chain has 900 stores.",
    sourceLabel: "Retail experimentation log (fictional)",
    prompt: "What is the strongest claim this data actually supports?",
    explanation: "Three urban flagship stores over two weeks is a narrow, non-representative slice: flagships aren't the median store, and two weeks won't catch seasonality or novelty decay. The +0.7pt is a real local signal worth chasing, but projecting it onto 900 mixed stores extrapolates far past the sample. The strongest claim treats it as a promising early read that warrants a broader test.",
    choices: [
      { text: "During the 2-week pilot, the 3 test stores converted about 0.7pt higher than their controls.", correct: false, rationale: "Too weak. A faithful description, but it stops short of the actionable read the pilot can responsibly bear." },
      { text: "The pilot is a promising early signal (~0.7pt lift), but 3 urban flagship stores over 2 weeks can't tell us chainwide impact — it warrants a larger, more varied rollout test.", correct: true, rationale: "Just right. Credits the signal, names the sample's limits, and points to the next decision without overreaching." },
      { text: "The redesigned checkout lifts conversion ~0.7pt and should be rolled out chainwide.", correct: false, rationale: "Over the line. Generalizes 3 non-representative stores to 900 and treats a 2-week estimate as a settled effect." },
      { text: "Rolling the flow out to all 900 stores would add about 0.7pt of conversion.", correct: false, rationale: "Over the line. Projects an n=3 point estimate onto the whole chain as if the sample were representative." },
    ],
  },
  {
    title: "The +2.1% that isn't",
    mode: "calibrate",
    skill: "certainty",
    difficulty: 3,
    contextSnippet: "**A/B test, conversion:** variant vs control, point estimate **+2.1%**, 95% CI **[-0.4%, +4.6%]**, p = 0.09. n = 24,000 per arm; test ran full 3 weeks as planned.",
    sourceLabel: "Experimentation platform (fictional)",
    prompt: "What is the strongest claim this data actually supports?",
    explanation: "The interval crosses zero and p = 0.09: the data is consistent with a small positive effect, no effect, or a tiny negative one. The point estimate is the center of a wide range, not a measured fact — stating \"+2.1% lift\" speaks a noisy reading as settled. The strongest honest claim reports the positive trend while making the uncertainty explicit.",
    choices: [
      { text: "The test is inconclusive, so we can't say anything about the variant.", correct: false, rationale: "Too weak. A non-significant positive trend is still information; this discards a directional signal the data does carry." },
      { text: "The variant trended positive (+2.1%), but the 95% CI (-0.4% to +4.6%) crosses zero, so the lift is suggestive, not established.", correct: true, rationale: "Just right. Reports the direction and size while making clear the effect isn't distinguishable from zero — honest about the noise." },
      { text: "The variant produced a 2.1% conversion lift.", correct: false, rationale: "Over the line. States the center of a zero-spanning interval as a settled effect — a noisy estimate spoken as certainty." },
      { text: "The variant lifts conversion 2.1%; ship it.", correct: false, rationale: "Over the line. Treats an unproven effect as fact and acts on it — the certainty error plus a decision it can't yet justify." },
    ],
  },
  {
    title: "What drove Q3",
    mode: "calibrate",
    skill: "single_cause",
    difficulty: 3,
    contextSnippet: "**Q3 revenue: +18% QoQ.** Concurrent changes in the quarter: list price **+6%**, entered **2 new metros**, **holiday** season, ad spend **~2×**. No decomposition or holdout run.",
    sourceLabel: "Growth review deck (fictional)",
    prompt: "What is the strongest claim this data actually supports?",
    explanation: "Four plausible drivers moved together — price, geography, seasonality, and spend — and nothing isolates their contributions. Crediting any one (or subset) is a single-cause pick over co-movers; the +18% could be any mix of them. The strongest defensible claim reports the aggregate and refuses attribution until a decomposition or controlled test separates the effects.",
    choices: [
      { text: "Q3 revenue rose 18% quarter over quarter.", correct: false, rationale: "Too weak. Accurate, but it abandons any analytic read; you can say more than the headline number while staying honest." },
      { text: "Revenue rose 18%, but price, two new metros, seasonality, and doubled ad spend all moved together — no single factor can be credited without a decomposition.", correct: true, rationale: "Just right. Reports the result and names why attribution is unavailable — the strongest claim four confounded drivers permit." },
      { text: "Entering the two new metros drove the 18% revenue gain.", correct: false, rationale: "Over the line. Picks one co-mover as the cause while three other factors moved simultaneously." },
      { text: "The price increase and higher ad spend together explain the 18% gain.", correct: false, rationale: "Over the line. Still attributes to a chosen subset while ignoring seasonality and the new metros — unsupported by any decomposition." },
    ],
  },
  {
    title: "Deflection after the chatbot launch",
    mode: "spot",
    skill: "buried_lede",
    difficulty: 2,
    contextSnippet: "**Helpdesk, post-chatbot launch:** self-serve deflection rate 34% (was 22%) · inbound tickets down 8,400/mo · CSAT flat at 4.2/5 · rollout completed in April",
    sourceLabel: "Support ops dashboard (fictional)",
    prompt: "Both tellings use the same numbers. Which one is poorly made because it buries the headline?",
    explanation: "The finding is a 12-point jump in deflection (22% to 34%) — that is the number a reader came for. The faithful telling leads with it; the flawed one opens with rollout logistics and methodology throat-clearing so the reader wades through three clauses before the result lands. Same facts, same honesty — the flaw is placement, not fidelity.",
    faithfulText: "Self-serve deflection rose to 34% after the chatbot launch, up from 22% — a 12-point jump that cut inbound tickets by about 8,400 a month, with CSAT holding at 4.2/5.",
    overclaimedText: "Following the April rollout, which completed across all queues, we reviewed deflection alongside CSAT and volume. Methodology held constant quarter over quarter. CSAT stayed at 4.2/5 and inbound tickets moved lower. On the deflection metric specifically, the self-serve rate — previously 22% — now reads 34%.",
    device: "the headline number arrives only after a paragraph of setup and secondary metrics",
  },
  {
    title: "Landing page conversion, to the thousandth",
    mode: "spot",
    skill: "false_precision",
    difficulty: 2,
    contextSnippet: "**Landing page A/B test:** variant B conversion 4.1% (78 of 1,900) · variant A 3.7% (70 of 1,880) · test ran 9 days",
    sourceLabel: "Growth experimentation log (fictional)",
    prompt: "Same result, same data. Which telling manufactures precision the sample cannot support?",
    explanation: "With 78 conversions out of 1,900, the rate is meaningful to about a tenth of a percent, not a thousandth — the next conversion or two swings it. Reporting '4.10526%' and a '0.38186pp lift' dresses sampling noise as measured signal. The honest telling rounds to the precision the counts can carry.",
    faithfulText: "Variant B converted at 4.1% versus 3.7% for A — roughly a 0.4-point lift on ~1,900 visitors each, promising but still thin at 78 conversions.",
    overclaimedText: "Variant B converted at 4.10526% versus 3.72340% for A, a lift of 0.38186 percentage points across the two arms.",
    device: "reporting decimals finer than the conversion counts can support",
  },
  {
    title: "Who actually uses the export feature",
    mode: "spot",
    skill: "missing_sowhat",
    difficulty: 3,
    contextSnippet: "**Analytics, new CSV export feature:** 18% of active accounts used export within 30 days · top-decile power users 3x more likely to use it · overall session time unchanged post-launch",
    sourceLabel: "Product analytics review (fictional)",
    prompt: "Both tellings are accurate and well-caveated. Which one is poorly made because it stops before the decision?",
    explanation: "Both statements are true and honestly hedged — but a readout exists to inform a choice. The flawed telling reports adoption, concentration, and the flat session time, then just stops; the reader is left holding facts with no lever. The good telling turns the same facts into a recommendation the team can act on or reject.",
    faithfulText: "Export reached 18% adoption in 30 days, but usage is concentrated in top-decile power users and hasn't moved session time — so hold further investment until we see it lift retention or expansion, rather than treating adoption as a win on its own.",
    overclaimedText: "Export reached 18% adoption in 30 days. Usage skews heavily to top-decile power users, who are 3x more likely to use it, and overall session time is unchanged since launch.",
    device: "true and caveated, but names no decision or action the reader can take",
  },
  {
    title: "Checkout redesign lift",
    mode: "spot",
    skill: "absent_caveat",
    difficulty: 3,
    contextSnippet: "**Ecommerce, checkout redesign:** conversion 1.9pp higher in the two weeks after launch · measurement window Nov 20–Dec 5 · desktop traffic only (mobile not yet migrated)",
    sourceLabel: "Conversion analytics (fictional)",
    prompt: "Both tellings report the same 1.9pp, without claiming cause. Which one omits a limitation the reader needs?",
    explanation: "Neither telling claims the redesign caused the lift, so this isn't a causation slip — both stay descriptive. The flaw is a dropped caveat: the window sits squarely on the holiday peak and covers desktop only, so the number won't generalize. The honest telling flags both constraints; the flawed one presents a clean 1.9pp that a reader will wrongly assume is representative.",
    faithfulText: "Conversion ran 1.9pp higher in the two weeks after launch — but the window (Nov 20–Dec 5) overlaps the holiday peak and covers desktop only, so treat it as provisional until we see a clean post-holiday read and mobile data.",
    overclaimedText: "Conversion ran 1.9pp higher in the two weeks after the checkout redesign launched, from Nov 20 to Dec 5.",
    device: "omitting the holiday-window and desktop-only limitations the reader needs to weight the number",
  },
  {
    title: "Monthly fraud model review",
    mode: "spot",
    skill: "padding",
    difficulty: 2,
    contextSnippet: "**Fraud model, monthly review:** precision 0.91 · recall 0.78 · 1,240 transactions flagged · 12 confirmed false negatives (missed fraud)",
    sourceLabel: "Risk modeling report (fictional)",
    prompt: "Same metrics, same conclusion. Which telling drowns the point in filler to look rigorous?",
    explanation: "The point is simple: precision is strong, recall is the weak spot, and 12 real frauds slipped through. The padded version restates the same facts three ways, wraps them in ceremonial hedging and process language, and buries the one actionable number — the 12 misses — under volume. Length is masquerading as rigor.",
    faithfulText: "The model holds precision at 0.91 but recall at 0.78 — of 1,240 flags it's accurate, yet it still missed 12 confirmed frauds. Recall is where to focus next.",
    overclaimedText: "As part of our ongoing and continuous monthly monitoring cadence, we conducted a thorough and comprehensive review of the fraud model's performance across the relevant evaluation period. It is worth noting, and important to emphasize, that the model demonstrated a precision figure of 0.91, which is to say that the vast majority of the 1,240 transactions surfaced by the system were indeed correctly identified. On the dimension of recall, the model registered a value of 0.78. In the interest of completeness, we would also observe that a certain number of fraudulent transactions — 12 in total — were not captured by the system and were subsequently confirmed as false negatives upon later review.",
    device: "the finding bloated with ceremony and restatement until the actionable point drowns",
  },
  {
    title: "Faster deliveries in June",
    mode: "spot",
    skill: "single_cause",
    difficulty: 1,
    contextSnippet: "**Swiftline Logistics, average door-to-door delivery time:** fell from **3.4 days to 2.6 days** in June. Three changes launched the same month: a **new routing algorithm**, **two additional regional depots**, and **weekend driver shifts**. Nothing was staggered or A/B tested.",
    sourceLabel: "Logistics operations dashboard (fictional)",
    prompt: "Which telling goes beyond what the data supports?",
    explanation: "Three delivery-speed levers went live in the same month, so the 0.8-day improvement belongs to the bundle, not any one piece. The faithful telling reports the drop alongside all three launches; the overclaim hands the whole gain to the routing algorithm, quietly dropping the depots and the weekend shifts. With nothing staggered or tested, that attribution is a choice, not a finding.",
    faithfulText: "Average delivery time fell from 3.4 to 2.6 days in June — the month the new routing algorithm, two new regional depots, and weekend driver shifts all launched together.",
    overclaimedText: "The new routing algorithm cut average delivery time from 3.4 days to 2.6 days in June.",
    device: "crediting the routing algorithm alone when three delivery changes launched the same month",
  },
  {
    title: "No-shows doubled in May",
    mode: "spot",
    skill: "buried_lede",
    difficulty: 1,
    contextSnippet: "**St. Alder clinic network, May scheduling report:** appointment no-shows **doubled from 6% to 12%** · SMS reminder system down **May 3–20** · phone reminders ran as normal · patient volume steady.",
    sourceLabel: "Clinic operations report (fictional)",
    prompt: "Both tellings use the same numbers. Which one is poorly made because it buries the headline?",
    explanation: "The story is one number: no-shows doubled, 6% to 12%. The faithful telling opens with it and uses the steady metrics and the SMS outage as context; the flawed one walks through routine review notes and secondary facts first, parking the doubling in the final sentence. Nothing is inaccurate — the finding is just hidden at the end.",
    faithfulText: "No-shows doubled in May, from 6% to 12% of appointments — coinciding with the May 3–20 SMS-reminder outage, while phone reminders and patient volume held steady.",
    overclaimedText: "We completed our monthly review of scheduling operations. Patient volume held steady, and phone reminders ran without interruption. The SMS reminder system was down May 3–20. Finally, appointment no-shows doubled, from 6% to 12%.",
    device: "the doubled no-show rate parked in the last sentence behind routine review notes",
  },
  {
    title: "Forty instructors, two decimals",
    mode: "spot",
    skill: "false_precision",
    difficulty: 1,
    contextSnippet: "**BrightPath (edtech), instructor survey on the new lesson planner:** **29 of 40** responding instructors said it saves them prep time. The survey was optional; **40 of 210** instructors responded.",
    sourceLabel: "Instructor research survey (fictional)",
    prompt: "Same result, same data. Which telling manufactures precision the sample cannot support?",
    explanation: "With 40 respondents, one instructor changing their answer moves the rate 2.5 points. The 72.50% is arithmetically exact for these 40 responders — the dishonesty is rhetorical: two decimals dress a small, optional sample as a measured constant. The faithful telling reports 29 of 40 — roughly three quarters — which is all the resolution the sampling frame can carry.",
    faithfulText: "Roughly three quarters of responding instructors — 29 of 40 — said the new lesson planner saves them prep time, a small optional sample worth reading as directional.",
    overclaimedText: "The survey finds that exactly 72.50% of responding instructors say the new lesson planner saves them prep time.",
    device: "quoting a 40-person survey to two decimal places",
  },
  {
    title: "The crash rate with no ask",
    mode: "spot",
    skill: "missing_sowhat",
    difficulty: 1,
    contextSnippet: "**Emberfall (mobile game), day-1 report on update 2.4:** **9%** of Android sessions crashed vs **0.6%** on iOS · crashes concentrated on devices with **under 3GB RAM** · update at **20% rollout**; pausing the rollout is a one-click option.",
    sourceLabel: "Mobile release monitoring dashboard (fictional)",
    prompt: "Both tellings are accurate and well-caveated. Which one is poorly made because it stops before the decision?",
    explanation: "Both tellings state the same facts and neither overreaches — but a day-1 crash readout exists to trigger a decision, and one names none. A 9% Android crash rate at 20% rollout with a one-click pause available points straight at an action; the flawed telling reports it and stops, leaving the reader to infer the move. The faithful one says it: pause Android until the crash on those devices is patched.",
    faithfulText: "The update crashes 9% of Android sessions versus 0.6% on iOS, concentrated on sub-3GB-RAM devices — pause the Android rollout at 20% until the crash on those devices is patched.",
    overclaimedText: "The new update crashes 9% of Android sessions versus 0.6% on iOS, with crashes concentrated on devices under 3GB of RAM. The rollout currently stands at 20%.",
    device: "a 9% day-1 crash rate reported with no pause, fix, or next step named",
  },
  {
    title: "Transfer volume and the $20 bonus",
    mode: "spot",
    skill: "absent_caveat",
    difficulty: 1,
    contextSnippet: "**Lumo (fintech app), instant-transfer volume:** **310,000 → 437,000** transfers in March (**+41%**). A **$20-per-transfer referral bonus ran the entire month** and ended March 31.",
    sourceLabel: "Payments growth dashboard (fictional)",
    prompt: "Both tellings report the same 41% jump, without claiming cause. Which one omits a limitation the reader needs?",
    explanation: "Both tellings stay descriptive — neither claims what caused the jump. But the $20-per-transfer bonus ran the entire measurement window, and the flawed telling drops it; a reader repeating '41% growth' will carry that number into forecasts without the one fact most likely to change how it reads. The faithful telling states the catch alongside the claim and marks the jump provisional.",
    faithfulText: "Instant transfers rose 41% in March, 310,000 to 437,000 — though the $20-per-transfer referral bonus ran the entire month and ended March 31, so treat the jump as provisional until April shows whether it holds.",
    overclaimedText: "Instant transfers came in at 437,000 for March, up 41% from February's 310,000 — a sizable jump in usage of the feature.",
    device: "omitting that a $20-per-transfer bonus ran the entire month being measured",
  },
];
