// Regenerate prisma/quiz.ts from the source JSON in prisma/quiz-source/.
// Run: node scripts/gen-quiz.mjs   (after editing the source JSON)
// The generated file inlines the item data (like prisma/drills.ts) and exports
// syncQuizItems for the seed + prod-init paths.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "prisma", "quiz-source");
const stats = JSON.parse(readFileSync(join(SRC, "statistics.json"), "utf8"));
const arch = JSON.parse(readFileSync(join(SRC, "architecture.json"), "utf8"));

const STATS_TOPICS = ["sampling", "variation", "association", "base_rates", "uncertainty", "aggregation"];
const ARCH_TOPICS = ["storage", "processing", "modeling", "scaling", "reliability", "cost"];

function check(items, track, topics) {
  const titles = new Set();
  for (const it of items) {
    if (!topics.includes(it.topic)) throw new Error(`${track}: bad topic ${it.topic} in ${it.title}`);
    if (![1, 2, 3].includes(it.difficulty)) throw new Error(`${track}: bad difficulty in ${it.title}`);
    if (it.choices.filter((c) => c.correct).length !== 1) throw new Error(`${track}: not exactly one correct in ${it.title}`);
    if (it.choices.length < 2) throw new Error(`${track}: too few choices in ${it.title}`);
    if (titles.has(it.title)) throw new Error(`${track}: dup title ${it.title}`);
    titles.add(it.title);
    for (const k of ["scenario", "prompt", "explanation"]) if (!it[k] || !String(it[k]).trim()) throw new Error(`${track}: empty ${k} in ${it.title}`);
  }
}
check(stats, "statistics", STATS_TOPICS);
check(arch, "architecture", ARCH_TOPICS);

const toSeed = (it, track) => ({
  track,
  title: it.title,
  topic: it.topic,
  difficulty: it.difficulty,
  scenario: it.scenario,
  prompt: it.prompt,
  choices: it.choices.map((c) => ({ text: c.text, correct: !!c.correct, rationale: c.rationale })),
  explanation: it.explanation,
});
const seeds = [...stats.map((it) => toSeed(it, "statistics")), ...arch.map((it) => toSeed(it, "architecture"))];

const out = `// AUTO-GENERATED by scripts/gen-quiz.mjs — do not hand-edit item content here.
// Edit the source JSON in prisma/quiz-source/ and rerun \`node scripts/gen-quiz.mjs\`.
// The seed pool for the two Training Room tracks (statistics, data-engineering
// architecture). Each item is a multiple-choice question with exactly one
// correct choice, stored as JSON on QuizItem; the serving path sends only
// shuffled { i, text }. Isolated world — imports nothing from the overclaim drill.
import type { PrismaClient } from "@prisma/client";

export type QuizChoice = { text: string; correct: boolean; rationale: string };
export type QuizSeed = {
  track: "statistics" | "architecture";
  title: string; // stable natural key for idempotent sync
  topic: string;
  difficulty: 1 | 2 | 3;
  scenario: string;
  prompt: string;
  choices: QuizChoice[]; // exactly one correct
  explanation: string;
};

export const QUIZ_SEEDS: QuizSeed[] = ${JSON.stringify(seeds, null, 2)};

// Idempotent content sync: upsert every seed by its stable title. Runs on every
// build (scripts/prod-init.ts) so both track pools ship without a reseed. The
// update path omits rating/attempts, preserving each item's learned difficulty
// across content edits. Prisma-only import — never ships to a client.
export async function syncQuizItems(prisma: PrismaClient): Promise<number> {
  for (const q of QUIZ_SEEDS) {
    const data = {
      track: q.track,
      topic: q.topic,
      scenario: q.scenario,
      prompt: q.prompt,
      choices: JSON.stringify(q.choices),
      explanation: q.explanation,
      difficulty: q.difficulty,
    };
    await prisma.quizItem.upsert({
      where: { title: q.title },
      create: { title: q.title, ...data },
      update: data,
    });
  }
  return QUIZ_SEEDS.length;
}
`;

writeFileSync(join(ROOT, "prisma", "quiz.ts"), out);
console.log(`wrote prisma/quiz.ts with ${seeds.length} items (${stats.length} statistics, ${arch.length} architecture)`);
