// Regenerate prisma/quiz.ts from the source JSON in prisma/quiz-source/.
// Run: node scripts/gen-quiz.mjs   (after editing the source JSON)
// The generated file inlines the item data (like prisma/drills.ts) and exports
// syncQuizItems for the seed + prod-init paths.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "prisma", "quiz-source");
const stats = JSON.parse(readFileSync(join(SRC, "statistics.json"), "utf8"));
const arch = JSON.parse(readFileSync(join(SRC, "architecture.json"), "utf8"));
const estimate = JSON.parse(readFileSync(join(SRC, "estimate.json"), "utf8"));
const duel = JSON.parse(readFileSync(join(SRC, "duel.json"), "utf8"));

const STATS_TOPICS = ["sampling", "variation", "association", "base_rates", "uncertainty", "aggregation"];
const ARCH_TOPICS = ["storage", "processing", "modeling", "scaling", "reliability", "cost"];

function check(items, track, topics) {
  const titles = new Set();
  for (const it of items) {
    if (!topics.includes(it.topic)) throw new Error(`${track}: bad topic ${it.topic} in ${it.title}`);
    if (![1, 2, 3].includes(it.difficulty)) throw new Error(`${track}: bad difficulty in ${it.title}`);
    if (it.choices.filter((c) => c.correct).length !== 1) throw new Error(`${track}: not exactly one correct in ${it.title}`);
    if (it.choices.length < 2) throw new Error(`${track}: too few choices in ${it.title}`);
    if (titles.has(it.title)) throw new Error(`${track}: dup title ${it.title}`);
    titles.add(it.title);
    for (const k of ["scenario", "prompt", "explanation"]) if (!it[k] || !String(it[k]).trim()) throw new Error(`${track}: empty ${k} in ${it.title}`);
  }
}
check(stats, "statistics", STATS_TOPICS);
check(arch, "architecture", ARCH_TOPICS);

// --- validators for the new interaction kinds --------------------------------
function checkEstimate(items) {
  const titles = new Set();
  for (const it of items) {
    if (!STATS_TOPICS.includes(it.topic)) throw new Error(`estimate: bad topic ${it.topic} in ${it.title}`);
    if (![1, 2, 3].includes(it.difficulty)) throw new Error(`estimate: bad difficulty in ${it.title}`);
    const { min, max, truth, good } = it;
    if (!(min < good.lo && good.lo < truth && truth < good.hi && good.hi < max))
      throw new Error(`estimate: ordering invariant broken in ${it.title}`);
    if (titles.has(it.title)) throw new Error(`estimate: dup title ${it.title}`);
    titles.add(it.title);
    for (const k of ["scenario", "prompt", "explanation"]) if (!it[k] || !String(it[k]).trim()) throw new Error(`estimate: empty ${k} in ${it.title}`);
  }
}
function checkDuel(items) {
  const titles = new Set();
  for (const it of items) {
    if (!ARCH_TOPICS.includes(it.topic)) throw new Error(`duel: bad topic ${it.topic} in ${it.title}`);
    if (![1, 2, 3].includes(it.difficulty)) throw new Error(`duel: bad difficulty in ${it.title}`);
    if (it.better !== "A" && it.better !== "B") throw new Error(`duel: better must be A|B in ${it.title}`);
    for (const d of [it.designA, it.designB]) {
      if (!d.name || !d.sketch || !Array.isArray(d.bullets) || d.bullets.length < 1)
        throw new Error(`duel: malformed design in ${it.title}`);
    }
    if (titles.has(it.title)) throw new Error(`duel: dup title ${it.title}`);
    titles.add(it.title);
    for (const k of ["constraint", "scenario", "deskRationale", "failureMode"]) if (!it[k] || !String(it[k]).trim()) throw new Error(`duel: empty ${k} in ${it.title}`);
  }
}
checkEstimate(estimate);
checkDuel(duel);

const mcqSeed = (it, track) => ({
  track,
  title: it.title,
  topic: it.topic,
  kind: "mcq",
  difficulty: it.difficulty,
  scenario: it.scenario,
  prompt: it.prompt,
  choices: it.choices.map((c) => ({ text: c.text, correct: !!c.correct, rationale: c.rationale })),
  payload: null,
  explanation: it.explanation,
});
const estimateSeed = (it) => ({
  track: "statistics",
  title: it.title,
  topic: it.topic,
  kind: "estimate",
  difficulty: it.difficulty,
  scenario: it.scenario,
  prompt: it.prompt,
  choices: [],
  payload: { unit: it.unit, min: it.min, max: it.max, truth: it.truth, good: it.good },
  explanation: it.explanation,
});
const duelSeed = (it) => ({
  track: "architecture",
  title: it.title,
  topic: it.topic,
  kind: "duel",
  difficulty: it.difficulty,
  scenario: it.scenario,
  prompt: "Which design fits these constraints?",
  choices: [],
  payload: {
    constraint: it.constraint,
    designA: it.designA,
    designB: it.designB,
    better: it.better,
    deskRationale: it.deskRationale,
    failureMode: it.failureMode,
  },
  explanation: it.deskRationale,
});
const seeds = [
  ...stats.map((it) => mcqSeed(it, "statistics")),
  ...arch.map((it) => mcqSeed(it, "architecture")),
  ...estimate.map(estimateSeed),
  ...duel.map(duelSeed),
];

const out = `// AUTO-GENERATED by scripts/gen-quiz.mjs — do not hand-edit item content here.
// Edit the source JSON in prisma/quiz-source/ and rerun \`node scripts/gen-quiz.mjs\`.
// The seed pool for the two Training Room tracks (statistics, data-engineering
// architecture). Each item is a multiple-choice question with exactly one
// correct choice, stored as JSON on QuizItem; the serving path sends only
// shuffled { i, text }. Isolated world — imports nothing from the overclaim drill.
import type { PrismaClient } from "@prisma/client";

export type QuizChoice = { text: string; correct: boolean; rationale: string };
export type QuizKind = "mcq" | "estimate" | "duel";
export type QuizSeed = {
  track: "statistics" | "architecture";
  title: string; // stable natural key for idempotent sync
  topic: string;
  kind: QuizKind;
  difficulty: 1 | 2 | 3;
  scenario: string;
  prompt: string;
  choices: QuizChoice[]; // mcq: exactly one correct; estimate/duel: []
  payload: unknown | null; // kind-specific: estimate band / duel designs+desk
  explanation: string;
};

export const QUIZ_SEEDS: QuizSeed[] = ${JSON.stringify(seeds, null, 2)};

// Idempotent content sync: upsert every seed by its stable title. Runs on every
// build (scripts/prod-init.ts) so both track pools ship without a reseed. The
// update path omits rating/attempts, preserving each item's learned difficulty
// across content edits. Prisma-only import — never ships to a client.
export async function syncQuizItems(prisma: PrismaClient): Promise<number> {
  for (const q of QUIZ_SEEDS) {
    const data = {
      track: q.track,
      topic: q.topic,
      kind: q.kind,
      scenario: q.scenario,
      prompt: q.prompt,
      choices: JSON.stringify(q.choices),
      payload: q.payload == null ? null : JSON.stringify(q.payload),
      explanation: q.explanation,
      difficulty: q.difficulty,
    };
    await prisma.quizItem.upsert({
      where: { title: q.title },
      create: { title: q.title, ...data },
      update: data,
    });
  }
  return QUIZ_SEEDS.length;
}
`;

writeFileSync(join(ROOT, "prisma", "quiz.ts"), out);
console.log(`wrote prisma/quiz.ts with ${seeds.length} items (${stats.length} statistics, ${arch.length} architecture)`);
